---  
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
      name: jaeger   
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: collector-config
    namespace: jaeger
  data:
    collector.yaml: |
      receivers:
        otlp:
          protocols: 
            grpc:
      processors:
      exporters:
        otlp:
          endpoint: "0.0.0.0:8126"
          tls:
           insecure: true
        datadog:
          api:
            key: "<Datadog API key>"
            site: datadoghq.eu
        logging:
      batch:
        timeout: 10s  
      k8sattributes:
        passthrough: true
      service:
        pipelines:
          traces:
            receivers: [otlp]
            processors: [batch, resourcedetection, k8sattributes]
            exporters: [logging, datadog, otlp]  